src/DNAnalyzer/Main.java
src/DNAnalyzer/Properties.java
src/DNAnalyzer/ProteinFinder.java
src/DNAnalyzer/ReadingFrames.java

- Added java doc for a few methods. 
- Did some inline documentation for unclear implementations
- Avoided documenting the obvious stuff

resolves #90: added and update java docs

---

src/DNAnalyzer/CoreExecutor.java
src/DNAnalyzer/Main.java
src/DNAnalyzer/Properties.java
src/DNAnalyzer/ProteinAnalysis.java

Marked methods in utility classes as static and changed their invocations.

Refactor for Utility classes - Issue #84

---

src/DNAnalyzer/AminoAcidMapping.java
src/DNAnalyzer/CoreExecutor.java
src/DNAnalyzer/Properties.java
src/DNAnalyzer/ProteinAnalysis.java
src/DNAnalyzer/ProteinFinder.java

Replace arraylist with list
Add constructor for ProteinFinder class
closes #72

Refactor ProteinFinder.getProtein with many args

---

src/DNAnalyzer/CoreExecutor.java

Implement ReadingFrame from user input as https://github.com/Verisimilitude11/DNAnalyzer/issues/104

Get ReadingFrame from user input

---

src/DNAnalyzer/Properties.java

Refactorings of the Properties.countNucleotides method

#74 refactoring of Properties.countNucleotides method

---

src/DNAnalyzer/CodonDataConstants.java
src/DNAnalyzer/CodonDataUtils.java

Fix for #75 as part of hacktoberfest

Refactor getAminoAcid method with reduced branches

---

README.md
src/DNAnalyzer/CodonDataConstants.java
src/DNAnalyzer/CodonDataUtils.java
src/DNAnalyzer/CoreExecutor.java
src/DNAnalyzer/Properties.java

Refactor getAminoAcid

---

README.md
src/main/java/DNAnalyzer/CmdArgs.java

This allows the user to reverse the DNA before processing it, through the `-r` or `--reverse` command-line argument.

Reverse option

---

src/test/java/DNAnalyzer/MainTest.java

removed instantiation of class with only static methods

---

README.md
docs/Contribution Guideline/Contribution_Guideline.md

Updated contributors in main readme.md

---

README.md

Signed-off-by: Zack Rhodes <zackrhodes86@gmail.com>

Added inline video, removed markdown

---

src/main/java/DNAnalyzer/AminoAcid.java
src/main/java/DNAnalyzer/AminoAcidFactory.java
src/main/java/DNAnalyzer/Properties.java

closes #76 
Print protein list refatorings

#76 refactor print protein list

---

docs/wiki-Home.md

Add Wiki markdown

---

src/main/java/DNAnalyzer/CmdArgs.java
src/main/java/DNAnalyzer/Dna.java
src/main/java/DNAnalyzer/DnaAnalyzer.java

Closes https://github.com/Verisimilitude11/DNAnalyzer/issues/189

Refactor CmdArgs

---

README.md

https://docs.gradle.org/current/userguide/compatibility.html Also adding link on how to download gradle

Changing wording, Gradle may not work with JDK 19.

---

src/main/java/DNAnalyzer/codon/CodonDataConstants.java

This is my attempt to solve issue #224 
I reduced the block length to less than 15 lines (11 lines).
Is that way ok?
If you have any remarks, please let me know.

Refactor CodonDataConstants

---

README.md

#228 #230 are the new future improvements I've added to the read.md file.

Added some new future improvements to the read.md

---

README.md

fixed typo in link

---

.classpath
.github/dependabot.yml

Added Dependabot configuration to automatically check for updates on dependencies on a weekly basis. It will also create a PR whenever there is an update.
Fixes - https://github.com/Verisimilitude11/DNAnalyzer/issues/262

Added Dependabot Configuration

---

web/index.js

Use const declarations for variables that are never reassigned

---

README.md

Adding information about DNA to README

---

.deepsource.toml
build.gradle

#252 Added the ability to publish to GitHub Packages.
./gradlew publish -Pgpr.user=username -Pgpr.key=token
You will need to add your username/token from your settings to publish this.  You can also add them to your local ~/.gradle/gradle.properties file and then you can just use: ./gradlew publish

Issue 252 publish gradle package

---

src/main/java/DNAnalyzer/BasePairCounter.java
src/main/java/DNAnalyzer/DNAAnalysis.java
src/main/java/DNAnalyzer/Properties.java
src/test/java/DNAnalyzer/DNAAnalysisTest.java

Closes #275
- contains BasePairCounter - a class responsible for counting nucleotides in given dna string
- other small refactorings

Refactorings of DNAAnalysis.countBasePairs(String)

---

src/main/java/DNAnalyzer/codon/CodonFrame.java

Undocumented declaration found

---

src/main/java/DNAnalyzer/aminoAcid/AminoAcid.java
src/main/java/DNAnalyzer/codon/CodonDataConstants.java
src/main/java/DNAnalyzer/codon/CodonDataUtils.java

I open this PR as part of Strengthening the  codebase of DNAnalyzer.
Closes #276.

Refactoring #276

---

README.md

Updating correct wording for feature

---

src/main/java/DNAnalyzer/Main.java
src/main/java/DNAnalyzer/core/DNAAnalysis.java
src/main/java/DNAnalyzer/core/Properties.java
src/main/java/DNAnalyzer/data/aminoAcid/AminoAcid.java
src/main/java/DNAnalyzer/data/aminoAcid/AminoAcidFactory.java
src/main/java/DNAnalyzer/data/codon/CodonDataConstants.java
src/main/java/DNAnalyzer/data/codon/CodonDataUtils.java
src/main/java/DNAnalyzer/data/codon/CodonFrame.java
src/main/java/DNAnalyzer/ui/cli/CmdArgs.java
src/main/java/DNAnalyzer/ui/gui/DNAnalyzerGUI.java
src/main/java/DNAnalyzer/ui/gui/DNAnalyzerGUIFXMLController.java
src/main/java/DNAnalyzer/utils/core/BasePairCounter.java
src/main/java/DNAnalyzer/utils/core/DNATools.java
src/main/java/DNAnalyzer/utils/core/ReadingFrames.java
src/main/java/DNAnalyzer/utils/core/Utils.java
src/main/java/DNAnalyzer/utils/protein/ProteinAnalysis.java
src/main/java/DNAnalyzer/utils/protein/ProteinFinder.java
src/test/java/DNAnalyzer/CodonDataUtilsTest.java
src/test/java/DNAnalyzer/DNAAnalysisTest.java
src/test/java/DNAnalyzer/ProteinFinderTest.java

New src code layout

---

README.md

Youtube is more popular and allows for a better viewing experience

Change tutorial video from OneDrive to Youtube

---

src/test/java/DNAnalyzer/DNAAnalysisTest.java
src/test/java/DNAnalyzer/MainTest.java
src/test/java/DNAnalyzer/ProteinFinderTest.java

Changed accessibility to Junit test classes and methods to package private

Refactor Junit test classes and methods to be package-private 

---

web/index.html
web/style.css

This commit adds a background video on the website of DNAnalyzer. I hope you like it!
Video by Pressmaster from Pexels: https://www.pexels.com/video/digital-formation-of-a-dna-in-an-animated-presentation-3191572/

Adds a background video to the website

---

src/main/java/DNAnalyzer/Main.java
src/main/java/DNAnalyzer/core/Properties.java
src/main/java/DNAnalyzer/utils/traits/Traits.java

closes #345 
- Removed unnecessary imports from 4 occurrences.

Unnecessary imports removed.

---

src/main/java/DNAnalyzer/ui/cli/CmdArgs.java

closes #344 
- Removed the boolean literals from `CmdArgs.java` file.

Boolean literal is redundant.

---

build.gradle
src/main/java/DNAnalyzer/ui/gui/DNAnalyzerGUIFXMLController.java
src/main/java/DNAnalyzer/ui/gui/DNAnalyzerRatingFXMLController.java
src/main/resources/DNAnalyzer/gui/fxml/DNAnalyzerGUI.fxml

Attached demo video to issue #332.
Closes #332

Add Rating GUI

---

src/main/java/DNAnalyzer/Main.java

There was a typo on the original prompt and I thought it could have better wording so the AI doesn't get confused.

Changed wording prompt to allow for better understanding for ChatGpt

---

build.gradle
src/main/java/DNAnalyzer/Main.java
src/main/java/DNAnalyzer/ui/gui/DNAnalyzerRatingFXMLController.java

This pull request introduces a new feature to the DNAnalyzer program - an AI-powered human-friendly analysis of DNA results. The feature uses the OpenAI GPT-3.5 language model to generate a paragraph-length summary of DNA analysis results that is both technical and easy for a biological researcher to understand. The feature is implemented in the Main class using the ChatGPT library and takes the output of the DNA analysis as input. The output of the AI analysis is then displayed on the console. This new feature enhances the user experience of the DNAnalyzer program by providing a more accessible and informative way to interpret DNA analysis results.

[AI] Human-friendly Analysis

---

src/main/java/DNAnalyzer/data/Parser.java
src/main/java/DNAnalyzer/ui/cli/CmdArgs.java

Creates a FASTA implementation that can handle comments, file names, and creates a framework for future file types.

Make a full FASTA implementation

---

src/main/java/DNAnalyzer/data/codon/CodonDataUtils.java
src/main/java/DNAnalyzer/utils/core/ReadingFrames.java
src/main/java/DNAnalyzer/utils/core/Utils.java
src/test/java/DNAnalyzer/core/DNAAnalysisTest.java
src/test/java/DNAnalyzer/data/codon/CodonDataUtilsTest.java
src/test/java/DNAnalyzer/utils/core/ReadingFramesTest.java

Improves buildCodonMap. Adds parallelized method; Selects between the non-parallelized or parallelized methods based on DNA string length. Resolves https://github.com/VerisimilitudeX/DNAnalyzer/issues/261

Parallelize build codon map

---

src/main/java/DNAnalyzer/utils/core/DNATools.java

I added the missing documentation

Added documentation to undocumented methods

---

web/about/about.html
web/analyzer/analyzer.html
web/index.html
web/style.css

---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/VerisimilitudeX/DNAnalyzer/pull/471?shareId=106d88d3-0905-4cff-bec6-8627934a0a6f).

Add visuals to the website

---

web/index.html
web/style.css

---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/VerisimilitudeX/DNAnalyzer/pull/480?shareId=901a645f-0a83-4855-8c3d-8be82a8f69bf).

Update scroll indicator on homepage

---

web/about/about.css
web/about/about.html
web/about/about.js
web/analyzer/analyzer.css
web/analyzer/analyzer.html
web/analyzer/analyzer.js
web/index.js
web/style.css

Enhance the website to be more user-friendly, modern, and interactive with a fresh startup theme.
* **HTML Changes:**
- Add interactive elements to the hero sections in `web/about/about.html` and `web/analyzer/analyzer.html`.
* **CSS Changes:**
- Add animations and transitions for interactive elements in `web/about/about.css` and `web/analyzer/analyzer.css`.
- Enhance team-section and analysis-container with hover effects and animations.
- Update contact-section and results-section with interactive elements and animations.
* **JavaScript Changes:**
- Add smooth scrolling and hover effects in the hero sections in `web/about/about.js` and `web/analyzer/analyzer.js`.
- Enhance team-section and analysis-container with JavaScript for hover effects and animations.
- Update contact-section and …

Enhance website with modern UI/UX

---

web/about/about.css
web/about/about.html
web/analyzer/analyzer.html
web/docs/docs.html
web/features/features.html
web/hiring/hiring-modal.css
web/hiring/hiring-modal.html
web/hiring/hiring-modal.js
web/hiring/hiring.css
web/hiring/hiring.html
web/hiring/hiring.js
web/index.html
web/server/server.html

---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/VerisimilitudeX/DNAnalyzer/pull/483?shareId=40cab0f9-d3ae-47c4-be6a-88c3c9512d7e).

Add hiring page and modal

---

web/about/about.html
web/analyzer/analyzer.html
web/index.html

---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/VerisimilitudeX/DNAnalyzer/pull/493?shareId=a29fcba1-cdb4-4bb9-8627-d85913df813b).

Update Twitter to X

---

web/analyzer/analyzer.css

---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/VerisimilitudeX/DNAnalyzer/pull/494?shareId=1c06db93-7af4-4229-9033-c1d032c9d362).

Fix overlapping checkmark options on Analyzer page

---

web/about/about.html
web/analyzer/analyzer.html
web/docs/docs.html
web/features/features.html
web/hiring/hiring.html
web/index.html
web/navbar.html
web/server/server.html

---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/VerisimilitudeX/DNAnalyzer/pull/497?shareId=131eb691-9ded-42c0-9a70-ab30592e1a4e).

Standardize navbar across all pages

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/VerisimilitudeX/DNAnalyzer/pull/499?shareId=bb739864-ec78-4cca-b667-30a696e309f9).

Append If DNAnalyzer helped, please ⭐ the repo to CLI output and issue templates

---

src/main/java/DNAnalyzer/utils/core/BasePairCounter.java

- update Javadoc description for `getCounts`
- `gradle test` *(fails: plugin `org.springframework.boot` not found)*

Clarify getCounts javadoc

---

src/test/java/DNAnalyzer/utils/protein/ProteinAnalysisTest.java

- expand `ProteinAnalysisTest` with a new test covering longest protein output
- `gradle test` *(fails: plugin org.springframework.boot not found)*

Add unit test for ProteinAnalysis

---

build.gradle
src/main/java/DNAnalyzer/qc/QcStats.java
src/main/java/DNAnalyzer/ui/cli/CmdArgs.java

- add `QcStats` for quick QC stats generation
- show QC summary and save chart when parsing DNA in CLI
- include jfreechart dependency
- add reports directory
- `gradle test` *(fails: Plugin org.springframework.boot was not found in any of the following sources)*

Add QcStats quality summary

---

README.md

- document Secure Share & Compare in the Development Roadmap
- `./gradlew test` *(fails: No route to host)*

Add Secure Share roadmap item

---

README.md
src/main/java/DNAnalyzer/adapter/AnalyseController.java
src/main/java/DNAnalyzer/adapter/FileController.java
src/main/java/DNAnalyzer/data/Parser.java
src/main/java/DNAnalyzer/utils/core/DNATools.java
src/test/java/DNAnalyzer/data/ParserTest.java
src/test/java/DNAnalyzer/utils/core/DNAToolsTest.java

- remove unused AnalyseController
- implement FileController to parse uploaded DNA files
- fix DNA validation for uppercase input
- improve Parser.parseFile handling of unknown types
- add tests for Parser and DNATools
- document new /api/file/parse endpoint
- `./gradlew test --offline` *(fails: No route to host)*

Fix parsing and add upload endpoint

---

README.md
web/about/about.html
web/analyzer/analyzer.html
web/assets/js/api-client.js
web/dashboard/dashboard.css
web/dashboard/dashboard.html
web/dashboard/dashboard.js
web/docs/docs.html
web/features/features.html
web/index.html
web/server/server.html

- create new web dashboard with file upload and Chart.js visualizations
- link to new page from site navigation
- update README to note dashboard uses REST API
- fetch API base URL from current host and use it in dashboard
- `./gradlew test` *(fails: No route to host while downloading gradle)*

Add interactive dashboard UI

---

src/main/java/DNAnalyzer/server/ApiController.java
src/main/java/DNAnalyzer/ui/cli/CmdArgs.java
src/main/java/DNAnalyzer/utils/alignment/SequenceAligner.java
src/test/java/DNAnalyzer/utils/alignment/SequenceAlignerTest.java

- implement simple Needleman–Wunsch global aligner
- expose an `/server/align` REST endpoint
- add `--align` CLI option to align the given sequence against a reference
- provide tests for SequenceAligner
- `gradle test` *(fails: Plugin [id: 'org.springframework.boot', version: '2.7.5'] was not found)*

Add sequence alignment feature

---

docs/developer/Plugin_Development.md
sample-plugins/README.md
sample-plugins/build.gradle
sample-plugins/src/main/java/example/DinucleotidePlugin.java
sample-plugins/src/main/resources/META-INF/services/DNAnalyzer.plugin.DNAnalyzerPlugin
src/main/java/DNAnalyzer/api/DNAnalyzerApiController.java
src/main/java/DNAnalyzer/plugin/DNAnalyzerPlugin.java
src/main/java/DNAnalyzer/plugin/PluginManager.java
src/main/java/DNAnalyzer/ui/cli/CmdArgs.java

- add DNAnalyzerPlugin interface
- add PluginManager for dynamic jar loading
- demo Dinucleotide plugin and build instructions
- document plugin development
- expose plugin option in CLI and API
- `./gradlew test` *(fails: No route to host)*

Implement plugin system

---

README.md
src/main/java/DNAnalyzer/data/trait/TraitPredictor.java
src/main/java/DNAnalyzer/ui/cli/CmdArgs.java

- note that trait predictions are for educational use only
- show a CLI disclaimer message after trait predictions
- document trait prediction disclaimer in README
- `./gradlew test` *(fails: Could not resolve all files for configuration)*

Add trait prediction disclaimer

---

docs/Development_Environment.md
docs/getting-started.md
scripts/start-dev-container.sh
src/main/java/DNAnalyzer/utils/ai/PathRouter.java

- convert natural language prompts to CLI args via OpenAI
- document `--nl` usage in the getting started guide
- `./scripts/run-tests.sh` *(fails: Could not resolve dependencies)*

Add natural language CLI

---

src/main/java/DNAnalyzer/ui/gui/DNAnalyzerGUI.java
src/main/java/DNAnalyzer/ui/gui/DNAnalyzerGUIFXMLController.java
src/main/resources/DNAnalyzer/gui/fxml/DNAnalyzerRating.fxml
src/main/resources/DNAnalyzer/gui/styles.css

- wire stylesheet into GUI and add rating dialog FXML
- use FileChooser in GUI controller to select DNA file
- add basic stylesheet to improve appearance
- `./gradlew assemble`
- `./gradlew test` *(fails: Could not resolve dependencies)*

Fix GUI FXML
