src/DNAnalyzer/CoreExecutor.java, src/DNAnalyzer/Main.java
Asks user to input the path to file for analysis.
@Verisimilitude11
The reason it didn't work before is that you closed the `Scanner`. When you close a `Scanner`, it also closes the underlying stream, which in this case is `System.in`, thus any other `Scanner` wrapping `System.in` will fail to read subsequent inputs.
Out of the 2 approaches (suppress the warning and not close / use a global `Scanner` and pass it around), I chose the latter as it is clear that `System.in` won't be needed after the `main()` function, so we can safely close it.
Feedback is welcome!
Closes #29.
=> Use user input filename for analysis

src/DNAnalyzer/CoreExecutor.java, src/DNAnalyzer/ProteinFinder.java
Refactored `CoreExecutor.createProteinList(String,String)`.
Removed the logic of passing down the amino acids as args to the `getProtein(String, String)` function and use `CodonData.getAminoAcid()` in `getProtein(String, String)` itself for better encapsulation.
=> resolves #80: Refactor CoreExecutor.createProteinList(String,String)

src/DNAnalyzer/CmdArgs.java
Uses regex because according to [this post](https://stackoverflow.com/a/38950317) it should be faster than `indexOf`
=> Protein finding

src/main/java/DNAnalyzer/CmdArgs.java, src/main/java/DNAnalyzer/CodonDataConstants.java
Reverts Verisimilitude11/DNAnalyzer#194
=> Revert "Refactor CodonDataConstants"

.github/workflows/static.yml
Currently the webpage can be shown by visiting <https://verisimilitude11.github.io/DNAnalyzer/web/>.
This PR should make it available without the `web/` path.
Closes #220.
=> Fix deploy github page workflow

.github/workflows/codeql-analysis.yml, build.gradle
Closes #268 and contains fix for tests run by gradle
- the analyzis action is fixed, added custom code build for 'java'
- is possible to run tests from command line using ./gradlew build
- added missing jupiter test engine
- enabled test results logging
=> Fix For Broken CodeQL Java Analysis

src/main/java/DNAnalyzer/DNAAnalysis.java
Condensed stream function into 2 instead of 3. I thought 3 lines made it more readable, but I guess not good coding style? It fits in less than 15 lines now per guidelines. resolves Verisimilitude11/DNAnalyzer#274
=> Condensed code in countBasePairs as to resolve #274

src/main/java/DNAnalyzer/CmdArgs.java, src/main/java/DNAnalyzer/DNAAnalysis.java
Closes #270.
Added highCoverageRegions output to CmdArgs
=> #270 Added highCoverageRegions call to CmdArgs

src/main/java/DNAnalyzer/Main.java, src/main/java/DNAnalyzer/core/Properties.java, src/main/java/DNAnalyzer/utils/traits/Traits.java
Reverts Verisimilitude11/DNAnalyzer#346
=> Revert "Unnecessary imports removed."

src/main/java/DNAnalyzer/core/Properties.java, src/test/java/DNAnalyzer/ProteinFinderTest.java, src/test/java/DNAnalyzer/core/PropertiesTest.java, src/test/java/DNAnalyzer/utils/core/DNAToolsTest.java, src/test/java/DNAnalyzer/utils/core/ReadingFramesTest.java, src/test/java/DNAnalyzer/utils/protein/ProteinAnalysisTest.java
Adds test cases for Properties, ReadingFrames, ProteinAnalysis and ProteinFinder class.
Closes #206
=> Add Additional testcases

.github/workflows/gradle.yml
The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Learn about it [here](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).
=> Update Gradle from V2 --> V2.3.3

src/main/java/DNAnalyzer/ui/cli/CmdArgs.java, src/test/java/DNAnalyzer/CodonDataUtilsTest.java
JUnit assertion methods expect the expected value to be the first argument
Closes #342.
=> Deepsource Wrong argument order in test assertions fix

README.md
Java updated it's link naming scheme so that when someone clicks this link, it actually goes to the Java 20 version instead of the Java 17 version.
=> Updating Java download link

src/main/java/DNAnalyzer/core/Properties.java, src/test/java/DNAnalyzer/core/PropertiesTest.java
=> refactor: Use stream.allMatch in isRandomDNA

README.md
I have added better Linux instructions for downloading Java and setting the JAVA_HOME path variable on Linux. If anyone has any other suggestions to add or change, please let me know as I'm not that great at Linux. I attempted this guide to downloading on a Linux Codespace VM and it worked.
=> Better Linux instructions for downloading

README.md, docs/contributing/CONTRIBUTING.md, docs/contributing/Contribution_Guidelines.md
Hello! I would like you add your repository to [this google doc](https://docs.google.com/document/d/1EjyQOwPO-Zc4aKM_mTPEFo3K97Ox3lEk-DyZxlivyVU/edit) as a bioinformatics-relevant hacktoberfest repo. To do so, I was checking the contribution guide (and open issues) and noticed some broken links and typos. I'm putting this PR in to clean those up.
=> fix typos and broken links in contribution guides

src/test/java/DNAnalyzer/utils/core/ReadingFramesTest.java
=> Fix Deepsource issues for #422

web/index.html, web/index.js, web/style.css
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/VerisimilitudeX/DNAnalyzer/pull/490?shareId=6c334b30-9d17-4446-be90-d108f51c1b5a).
=> Add product feature timeline view

web/analyzer/analyzer.js
Remove the pop-up message "API server is offline. Running in fallback mode with limited functionality." from the analyzer page.
* Remove the call to `showNotification` with the message in the `checkAPIStatus` function in `web/analyzer/analyzer.js`
* Remove the `showNotification` function call in the `checkAPIStatus` function in `web/analyzer/analyzer.js`
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/VerisimilitudeX/DNAnalyzer/pull/492?shareId=107f862a-d8dd-4cb3-afa9-2166100fb6ce).
=> Remove API server offline popup from analyzer page

src/main/java/DNAnalyzer/core/DNAAnalysis.java, src/test/java/DNAnalyzer/core/DNAAnalysisTest.java
- set ASCII values for unknown bases 'N' and 'n'
- verify counting of unknown bases in DNAAnalysisTest
- `gradle test` *(fails: Plugin [id: 'org.springframework.boot', version: '2.7.5'] was not found)*
=> Fix unknown base constants

README.md, assets/risk/heart_disease_prs.csv, src/main/java/DNAnalyzer/data/trait/TraitPredictor.java, src/main/java/DNAnalyzer/ui/cli/CmdArgs.java, src/test/java/DNAnalyzer/data/trait/TraitPredictorTest.java
- expand `TraitPredictor` with muscle performance and alcohol flush traits
- add 23andMe genotype and PRS options to command line
- compute trait predictions and polygenic risk score in CLI
- include sample heart disease weight file
- document usage for new features in README
- `./gradlew test` *(fails: No route to host while downloading gradle)*
=> Add trait predictions and PRS CLI support
